--
CREATE TABLE TB_CATEGORIAS (
  COD_CATEGORIA INT(10) NOT NULL COMMENT 'Código da categoria',
  NOM_CATEGORIA VARCHAR(50) NOT NULL COMMENT 'Nome da categoria',
  FLG_ATIVO VARCHAR(1) NOT NULL DEFAULT 'S' COMMENT 'Categoria ativa [S]im [N]ão',
  PRIMARY KEY (COD_CATEGORIA)
);
--
CREATE TABLE TB_PRODUTOS (
  COD_PRODUTO INT(10) NOT NULL COMMENT 'Código do produto',
  COD_CATEGORIA INT(10) NOT NULL COMMENT 'Código da categoria, relacionado com tb_categoria',
  COD_BARRAS VARCHAR(20) NOT NULL COMMENT 'código de barras para encontrar o produto',
  NOM_PRODUTO VARCHAR(50) NOT NULL COMMENT 'nome do produto',
  DES_PRODUTO VARCHAR(500) NOT NULL COMMENT 'Descrição longa do produto',
  FLG_ATIVO VARCHAR(1) NOT NULL DEFAULT 'S' COMMENT 'Produto ativo [S]im [N]ão',
  PRIMARY KEY (COD_PRODUTO, COD_CATEGORIA),
  CONSTRAINT TB_PRODUTOS_UK UNIQUE (COD_BARRAS ASC),
  CONSTRAINT CATEGORIA_PRODUTO_FK FOREIGN KEY (COD_CATEGORIA) REFERENCES TB_CATEGORIAS (COD_CATEGORIA)
);
--
